services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - /Users/chavdarbilyanski/energyscale/mlruns:/Users/chavdarbilyanski/energyscale/mlruns  # Mount host mlruns to same path in container (read-only)
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  ml:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ml
    env_file:
      - .env
volumes:
  pgdata: